name: premaster to master

on:
  push:
    branches:
      - premaster

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          base: master
          branch: pre-master
          title: 'Automated PR from pre-master to master'
          body: 'This is an automated pull request created by GitHub Actions'
          reviewers: 'tony-itilite,nayeem-itilite,madhusudhan-itilite'
          team-reviewers: 'Itilite Travel' # Replace with your team slug if using team reviewers

      - name: Send notification to Google Chat
        if: steps.create_pr.outputs.pull-request-url != ''
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{"text": "A new pull request has been created: ${{ steps.create_pr.outputs.pull-request-url }}"}' \
          $GOOGLE_CHAT_WEBHOOK

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: create-pull-request
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        uses: ahmadnassri/action-auto-merge-dependabot@v2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          PR: ${{ needs.create-pull-request.outputs.pull-request-number }}

      - name: Send notification to Google Chat
        if: success()
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{"text": "The pull request has been successfully merged into master."}' \
          $GOOGLE_CHAT_WEBHOOK
